import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="bg-slate-300 p-7 mb-20 flex gap-10">
          <Link href={`/#`}>Home</Link>
          <Link href={`/pages/company`}>Company</Link>
          <Link href={`/pages/team`}>Teams</Link>
          <Link href={`/pages/blog`}>Blog</Link>
          <Link href={`/pages/products`}>Products</Link>
        </header>
        {children}
        <footer className="bg-slate-300 p-7 mt-20">
          This is the footer
        </footer>
      </body>
    </html>
  );
}
